### ISSUE TITLE
焦煤/可乐

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [Kiwi233/Translation-of-GTNH#103]
GT++ 把仙人掌/糖 Coke 翻译成了仙人掌/糖可乐，优先级较高，因此游戏中显示的也是这个，请修正。

**Comment by Kiwi233** [comment]
请仔细查看汉化包

**Comment by WuzgXY-GitHub** [comment]
我知道汉化包中那个是对的，但游戏里它被 GT++ 自带的翻译给覆盖了，不然为什么会显示错
