### ISSUE TITLE
任务ID 2555 细节

### ISSUE THREAD

**Issue by AdminXiaoMai** [Kiwi233/Translation-of-GTNH#119]
GTNH 2.1.1.2
汉化版本 2.1.1.1a
7阶火箭
鸟神星
氢氯酸→工业氢氟酸
![image](https://user-images.githubusercontent.com/22012110/131041973-d6f52d1b-438e-45b3-bbc7-4a7f2db254e2.png)

**Comment by Kiwi233** [comment]
感谢反馈，已修正

**Comment by iouter** [comment]
@Kiwi233 2.1.1.3中此bug已被修复

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8502
