### ISSUE TITLE
汉化情况下 电子探矿机（mv）无法正常使用

### ISSUE THREAD

**Issue by firstdayofapril** [Kiwi233/Translation-of-GTNH#127]
![2021-10-25_23 56 40](https://user-images.githubusercontent.com/10325197/138730013-5661c907-1991-4b0b-853c-f72235576a78.png)
语言环境为简体中文状态下，使用效果
![2021-10-25_23 57 37](https://user-images.githubusercontent.com/10325197/138730123-e4c97a4e-7d36-435b-83a6-6c397fea1b5e.png)
语言环境为英语状态下，使用效果
版本为 2.1.1.2

**Comment by Kiwi233** [comment]
@albus12138 
求帮助

**Comment by albus12138** [comment]
之前和kiwi为了汉化探矿仪的输出，我在 GT Scanner 1.5.7 版本把原本硬编码的英文改为了语言文件，然后通过 GT_LanguageManager 从 Gregtech.lang 读取汉化的矿物名称，当时测试结果是自动生成的英文 Gregtech.lang 也会包含这些内容。

这个问题应该是修复这个issue时产生的， [#8092](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8092)，里面提到在 GTNH 2.1.1.0 出现英语环境下找不到 key 的问题，然后又改回了 StatCollector.translateToLocal，所以存在汉化找不到 key 导致返回空白文本的情况。

要解决这个问题还需要和GTNH开发组沟通一下。这个修复是 1.6.0 版本更新的，临时解决方案可以先回滚到 1.5.9 版本的 GT Scanner（GTNH 2.1.0.0），在 GTNH 2.1.1.2 测试可以正常使用，但没有 JourneyMap 插件兼容了 @firstdayofapril 。

**Comment by GlodBlock** [comment]
修了
