### ISSUE TITLE
新mod VisualProspecting

### ISSUE THREAD

**Issue by iouter** [Kiwi233/Translation-of-GTNH#131]
有新mod [VisualProspecting](https://github.com/GTNewHorizons/VisualProspecting)
注意assets内有gregtech/lang中有文件，是关于一些特定矿脉名称的。

**Comment by Kiwi233** [comment]
https://github.com/Kiwi233/Translation-of-GTNH/commit/260e2e1985ad0dba6e6111786c85657f33a16bf6
