### ISSUE TITLE
几个可以进行润色或改正的地方(Tier0,0.5,1)

### ISSUE THREAD

**Issue by Marco-V** [Kiwi233/Translation-of-GTNH#14]
安装并使用了汉化包有一段时间了，发现了一些需要润色或者改正的地方，由于不知道汉化组以什么方式标记任务，所以我先使用任务号代替吧，每一句话前面的数字是需要润色/改正的任务号，-代表建议改正的，→代表建议润色的。
因为目前我就玩到蒸汽时代，为了避免自己被严重剧透，所以就只说蒸汽时代以及之前的吧2333
update1:这是我第一次使用Github，不知道怎么搞的，就自带了删除线，还请看的时候忽略掉这些删除线→_→
update2:好吧我好像知道了，波浪线还不能随便用→_→，我把润色的标记改成→了
-----第0阶-----
1495：创意模式-创造模式
470：什锦梅-什锦莓（任务概述与标题不符，标题中使用正确，为“莓”，但概述中使用错误，为“梅”）
-----第0.5阶-----
1506：上网b-上网搜索（这个确定不是不小心按到键盘了？）
21：陶机-陶器
41：熔岩→岩浆（Minecraft原版当中Lava即为岩浆，同理，书中提到clay时有许多黏土和粘土混淆的地方，应追随Minecraft原版的翻译“粘土”而非“黏土”，之后的“熔岩”与“黏土”不一一列举。）
24：很多→正好的
1496：为了一路阅读，我会给你一块铁锭→看在你一路读下来的份上，给你块铁锭吧
480：小矿石→贫瘠矿石
480：带状铁矿脉-带状铁矿矿石
29：褐炭-褐煤
1790：（这个任务没有看到翻译，标题和内容都是，不知道是不是bug了）
473：剑魂-匠魂
693：殒石-陨石
1546：不是沙子-不是锡石矿砂
-----第1阶-----
60：煤炭锅炉→燃煤锅炉（包括标题和内容）
46：蒸气-蒸汽（不仅此处有此错误，别处的相同错误不一一列举）
52：你必须用凿子它来使用这个配方（原文我不知道，所以不提供建议修改方案，但是这句话肯定是不通顺的= =）
563：（最后一句话没加句号。别打我。）
835：电路扳-电路板
70：第2阶=-第2阶（多打了个 “=”，估计是手滑按到键盘了）
1789：（和1790一样）
742：捶子-锤子
742：地狱-下界（虽然我也习惯称nether为地狱吧→_→从1.0入坑的玩家...1.0的时候明明就是地狱的）

**Comment by Marco-V** [comment]
835那个是把电路板的板写成了扳手的扳了→_→

**Comment by Kiwi233** [comment]
咳咳 视力不太好 已修复
