### ISSUE TITLE
LootGames翻译错误

### ISSUE THREAD

**Issue by hoshinokiseki** [Kiwi233/Translation-of-GTNH#148]
[lootgames/lang/zh_CN.lang#L29](https://github.com/Kiwi233/Translation-of-GTNH/blob/81164d1a83d51e24de11140bb2026c783e995c3b/resources/lootgames/lang/zh_CN.lang#L29)
根据出现的位置，应翻译为 你剩余%d次机会 比较好。

**Comment by Kiwi233** [comment]
感谢反馈，已修正
