### ISSUE TITLE
服务端任务书汉化失败

### ISSUE THREAD

**Issue by liucmsz** [Kiwi233/Translation-of-GTNH#149]
想请教大家在服务端怎样汉化任务书 已经覆盖了汉化包 但是就没有转中文
已检查了 注意：2.0.6.2及以后版本在config文件夹内添加了带us后缀的json文件，请删除此文件，否则会造成任务书汉化失败

**Comment by liucmsz** [comment]
服务器和用户端都是2.1.2.1的版本

**Comment by Kiwi233** [comment]
客户端怎么弄服务端就怎么弄，注意读完说明。。。
