### ISSUE TITLE
enderFragment ToolTip

### ISSUE THREAD

**Issue by MuXiu1997** [Kiwi233/Translation-of-GTNH#154]
[`	<ToolTip ItemName="EnderZoo:enderFragment" ToolTip="§11H Use in Personal Chunkloader"/>`](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/GTNewHorizons/CustomToolTips.xml#L118)
[`	<ToolTip ItemName="EnderZoo:enderFragment" ToolTip="§在个人锚中可使用11小时"/>`](https://github.com/Kiwi233/Translation-of-GTNH/blob/master/config/GTNewHorizons/CustomToolTips.xml#L50)

```diff
-	<ToolTip ItemName="EnderZoo:enderFragment" ToolTip="§在个人锚中可使用11小时"/>
+	<ToolTip ItemName="EnderZoo:enderFragment" ToolTip="§1在个人锚中可使用1小时"/>
```

**Comment by Kiwi233** [comment]
感谢反馈，已修正
