### ISSUE TITLE
新版本粒子名称有误

### ISSUE THREAD

**Issue by YoungGT** [Kiwi233/Translation-of-GTNH#16]
Graviton 引力→引力子
Charm Quark 魅力夸克→粲夸克
Top Quark 顶部夸克→顶夸克
Bottom Quark 底部夸克→底夸克
Muon μ介子→μ子
Muon Neutrino μ中微子→μ子中微子
Tau τ介子→τ子
Tau Neutrino τ中微子→τ子中微子

**Comment by huajijam** [comment]
已修
