### ISSUE TITLE
[反馈]服务端覆盖汉化文件后任务书仍为英文

### ISSUE THREAD

**Issue by KevinKiller1213** [Kiwi233/Translation-of-GTNH#175]
RT
2.1.2.1版本服务端覆盖汉化文件后任务书仍为英文，us后缀json文件客户端及服务端已经删除，执行`/bq_admin default load 2`命令后提示没有找到任务数据，客户端在单机存档时任务书为中文。

**Comment by KevinKiller1213** [comment]
使用的是complete版本汉化包

**Comment by Kiwi233** [comment]
咳咳 指令为
/bq_admin default load
