### ISSUE TITLE
TC研究名字乱码

### ISSUE THREAD

**Issue by huajijam** [Kiwi233/Translation-of-GTNH#18]
当材质和mt文件同时加入文件时,巫术、血魔法、GTNH研究页名字丢失，出现原始TC研究名，
![image](https://user-images.githubusercontent.com/29218242/51722485-7ca3cd80-2090-11e9-96ce-9013d00f5675.png)
![image](https://user-images.githubusercontent.com/29218242/51722515-96ddab80-2090-11e9-8b20-5060aa5a63a0.png)
![image](https://user-images.githubusercontent.com/29218242/51722520-9ba25f80-2090-11e9-93d4-7d5d72206d13.png)

**Comment by Kiwi233** [comment]
这是在游戏内重载材质包就会这样
这时候重载下mt就行了

**Comment by huajijam** [comment]
服务器你告诉我mt reload

**Comment by Kiwi233** [comment]
那你就退出重进，别在游戏里换材质包就行了，还有这不是汉化的锅，是mt的锅
