### ISSUE TITLE
[反馈/建议]物品6954:8510翻译错误

### ISSUE THREAD

**Issue by Ch1sai556** [Kiwi233/Translation-of-GTNH#186]
其原文是Opal，Opal在宝石领域中应当翻译成欧泊或者蛋白石
物品6954:8510此处翻译为猫眼石
百度翻译和牛津词典把Opal翻译成蛋白石或猫眼石
而在查询相关学术文献后，前面未标注任何前缀的猫眼石应当专指金绿宝石的一种，金绿宝石从组成成分上与蛋白石相差迥异
金绿宝石为铍铝氧化物宝石，蛋白石Opal为多水二氧化硅宝石
在游戏中对物品6954:8510的化学式标注为Si02，更加接近多水二氧化硅
且游戏材质更倾向于表现欧泊或蛋白石的变彩效应
而非表示猫眼石的猫眼效应
所以这里认为采用蛋白石或者欧泊作为对Opal的翻译更为恰当

在这个问题上我也咨询了一下宝石学的老师
宝石学的老师说Opal翻译成猫眼石是错的，是有问题的
![聊天记录](https://user-images.githubusercontent.com/84222024/166445030-cfd48c0f-b94a-4d5a-a67b-7533d4030df9.png)

**Comment by Kiwi233** [comment]
非常感谢指正，将在下个版本修正

**Comment by n0099** [comment]
CFPA需要您
