### ISSUE TITLE
[反馈/建议]巨型机器tooltip

### ISSUE THREAD

**Issue by MuXiu1997** [Kiwi233/Translation-of-GTNH#214]
```
    S:TileEntity_DESCRIPTION_13366_Index_0=机器类型：§e§4分§5子§c手§d术§4机§r
    S:TileEntity_DESCRIPTION_13366_Index_8=添加者：§2§1V§35§58§77§a丶§b小§c天§d喵，模组：§2BartWorks§7
    S:TileEntity_DESCRIPTION_13367_Index_0=机器类型：§e§4化§5合§c键§d撕§5裂§4者§r
    S:TileEntity_DESCRIPTION_13367_Index_12=添加者：§2§1V§35§58§77§a丶§b小§c天§d喵，模组：§2BartWorks§7
```

内容与原文不符

需要署名请提交到gtnh代码库内
> Don't get too creative at machine type. It makes searching in NEI harder than it should be. Let's keep it the same as the non mega version.

机器类型同理，请提交到gtnh代码库内

@SKYCATV587

**Comment by Kiwi233** [comment]
https://github.com/Kiwi233/Translation-of-GTNH/commit/1d43bc5ee309f5ddc05ca4c3f671762fbdadce83

**Comment by Kiwi233** [comment]
等待贡献者修改署名提交至GTNH官方仓库
