### ISSUE TITLE
[反馈/建议]建议迁移到云汉化平台Paratranz

### ISSUE THREAD

**Issue by iouter** [Kiwi233/Translation-of-GTNH#224]
[Paratranz](https://paratranz.cn/)是一个可以免费使用，相对通用的游戏汉化平台。它具有翻译建议，专业名词搜索，历史版本追溯，注释，术语等等专业的翻译功能，也能更轻松的实现翻译协作。所以我建议把汉化工作迁移到Paratranz。
优点：
1. 拥有翻译建议，专业名词搜索，历史版本追溯，注释，术语等等专业的翻译功能。
2. 可以更加方便的协作汉化，参加汉化工作只需要一个github账号，不需要学会github的操作，也不会出现重复翻译等等问题。

问题：
1. 不支持MC的lang文件，只支持json和csv，需要单独适配。
2. 目前的翻译流程需要修改，比如导出结果后需要重新还原成lang文件（更别提zs），不过应该可以实现自动化。
3. 可能没有那么多人参加汉化工作。

**Comment by iouter** [comment]
<del>吹一波paratranz</del>

**Comment by Kiwi233** [comment]
唔 我去了解一下

**Comment by Discreater** [comment]
zs文件 可能可以把整个文件都作为一个条目，这样就不需要解析和还原了

**Comment by Discreater** [comment]
确实整个文件太长了，话说zs文件里需要汉化的部分只有 `game.setLocalization(...) ` 这些语句吗？

**Comment by iouter** [comment]
还有些别的，但终究都是有规律的

**Comment by Discreater** [comment]
我在vscode里用正则表达式搜了一下，scripts里已经被汉化的语句应该只有下面这些：

- game.setLocalization...
- NEI.overrideName...
- .*.displayName = ...
- .*.addTooltip...
- .*.addShiftTooltip...
- .*.addPage...

---

附正则语句

假设汉化后的文本都包含 `\u`。

包含 `\u` ，且 `\u` 之前有双引号（过滤文本过长换行之后的文本）的所有行（可搜到1000多项）
```regex
.*".*\\u.*
```

去掉上述列表中所有条目的包含 `\u` 的所有行（搜到0项，证明前面的列表包含了所有情况）
```regex
^(?!((game.setLocalization)|(NEI.overrideName)|(.*\.((displayName = )|(addTooltip)|(addShiftTooltip)|(addPage))))).*".*\\u.*
```

如果有遗漏欢迎指正。

**Comment by MuXiu1997** [comment]
- #285
