### ISSUE TITLE
漏掉一个任务，史蒂大(fu)23333

### ISSUE THREAD

**Issue by DonkeyTao** [Kiwi233/Translation-of-GTNH#25]
![1](https://user-images.githubusercontent.com/31684122/59619750-d13e0700-915d-11e9-93a9-42d8901cb017.png)

![2](https://user-images.githubusercontent.com/31684122/59619763-d7cc7e80-915d-11e9-83d9-f36d450b6fc6.png)

**Comment by Kiwi233** [comment]
这个任务是大鸡蛋拆干细胞的，早就不能用了，我已经跟作者说过了，不知为啥没删掉。。。

**Comment by Kiwi233** [comment]
另外，史蒂大是故意的，原文在玩文字游戏
