### ISSUE TITLE
[反馈/建议]潘马斯和openprinter汉化问题

### ISSUE THREAD

**Issue by Merrg1n** [Kiwi233/Translation-of-GTNH#252]
1. 潘马斯农场mod现有翻译问题太多（如备货->底汤），是否可以参考1.12 [Minecraft-Mod-Language-Package](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package) 的翻译，另附一个移植后的翻译文件[zh_CN.txt](https://github.com/Kiwi233/Translation-of-GTNH/files/9613950/zh_CN.txt)
2. openprinter似乎存在乱码问题
![image](https://user-images.githubusercontent.com/22628584/191437688-9ad21efe-e04f-41ed-8571-7396fb09d0c2.png)
3. （在尝试修复以上问题时发现）resources文件夹直接修改lang文件似乎没有起效，前两个mod包内assets内带有zh_CN.lang文件，这也导致前两个问题。可能的解决办法：打包成resourcepack后在游戏中显式使用资源包

**Comment by Kiwi233** [comment]
https://github.com/GTNewHorizons/OpenPrinter/pull/2

**Comment by Kiwi233** [comment]
OpenPrinter这个其实早就有修复，只是原作者一直没有打包进去，现GTNH已重新打包，新版本应该可以修复
