### ISSUE TITLE
GT语言文件里的“覆盖版”“覆盖板”

### ISSUE THREAD

**Issue by DonkeyTao** [Kiwi233/Translation-of-GTNH#27]
![20190814212134](https://user-images.githubusercontent.com/31684122/63024309-86303e00-bed9-11e9-8e58-143f29fa7096.png)

**Comment by Kiwi233** [comment]
历史遗留问题，GT5语言文件就是这样，大家都习惯了所以也就没改，类似的还有仓(舱)，不过既然提出来了，我找时间统一改吧
