### ISSUE TITLE
[提醒] 2.2.0.0版本汉化存在的较大问题

### ISSUE THREAD

**Issue by ChromicRedBrick** [Kiwi233/Translation-of-GTNH#273]
1. GT++本地化失效；
2. GT蜂窝本地化失效；
3. NEI 任务书跳转页面没有本地化；
4. gendustry汉化未覆盖（这个直接拿汉化文件去交pr就行）

**Comment by iouter** [comment]
可以确定，出现方法的问题分别是在：
1.[GTPP-getItemStackDisplayName](https://github.com/GTNewHorizons/GTplusplus/blob/07e4dc0f89ae1eae30e59631797eae4787abd299/src/main/java/gtPlusPlus/core/item/base/BaseItemComponent.java#L183)
2.[GT5-getName](https://github.com/GTNewHorizons/GT5-Unofficial/blob/3964f316f2824ce2d241aa7c59364d6479b05b0a/src/main/java/gregtech/common/items/CombType.java#L236)（[GT5-getItemStackDisplayName](https://github.com/GTNewHorizons/GT5-Unofficial/blob/3964f316f2824ce2d241aa7c59364d6479b05b0a/src/main/java/gregtech/common/items/ItemComb.java#L94)）

疑似对于getItemStackDisplayName这个方法，GT_LanguageManager的addStringLocalization方法只能返回原文（getTranslation也不行）。在实际游戏中，只会显示原文，即使控制台里可以输出翻译后的结果。

**Comment by ChromicRedBrick** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11570

**Comment by 8608029714** [comment]
请问这玩意修复了么

**Comment by iouter** [comment]
发pr了，没人审查，所以没合并

**Comment by iouter** [comment]
prim通过了，下个版本应该就正常了

**Comment by iouter** [comment]
已修复

**Comment by 8608029714** [comment]
请问替换了两个mod还是英文？应该怎么搞？

**Comment by ChromicRedBrick** [comment]
> 请问替换了两个mod还是英文？应该怎么搞？

如果要现在体验修复内容的话，得全部升级整合包，或者至少是升级所有GT相关的核心mod

（可能会带来测试版的其他游戏内容bug）

**Comment by 8608029714** [comment]
好的谢谢，我以为替换掉这两个修复的mod就行了呢，看来还要在等等了

**Comment by iouter** [comment]
蜂窝应该直接正常了；因为我改了汉化格式和key，所以gtpp材料还去需要汉化gregtech.lang。

**Comment by iouter** [comment]
升级这俩就够了，只是需要等汉化，或者你可以自己搞一份临时的。

**Comment by 8608029714** [comment]
那可就力不从心了  ：（

**Comment by chixiguavv1** [comment]
是我的问题吗? 搞了一份临时的  框架(frame box)的无法汉化。有一部分也无法再gregtech.lang中找到。
![铜金合金](https://user-images.githubusercontent.com/115782245/195799696-4fe36793-81f4-46ad-a190-e4705240ce6a.png)
![image](https://user-images.githubusercontent.com/115782245/195799768-9d9aef52-41d4-43ef-845e-86726b2caed4.png)

**Comment by ChromicRedBrick** [comment]
应该是现在用%material的问题了

得重新汉化

**Comment by iouter** [comment]
那就是没完全修好，我再去看看

**Comment by iouter** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/404 框架

**Comment by 8608029714** [comment]
这个合并之后替换mod就能显示中文了？

**Comment by iouter** [comment]
还得汉化gt.lang

**Comment by chixiguavv1** [comment]
![image](https://user-images.githubusercontent.com/115782245/196218452-a418d2b7-bbb8-4669-8d6c-2d7aae96b597.png)
双重板无法汉化

**Comment by chixiguavv1** [comment]
![image](https://user-images.githubusercontent.com/115782245/196218749-d7cf7c31-4944-49e7-b4e8-1a63dbd21eaf.png)
这种没有用%material的能汉化吗

**Comment by iouter** [comment]
> ![image](https://user-images.githubusercontent.com/115782245/196218452-a418d2b7-bbb8-4669-8d6c-2d7aae96b597.png) 双重板无法汉化

![image](https://user-images.githubusercontent.com/62897714/196231985-af5b4844-6a24-45ff-8875-dc3625426ee5.png)
没什么可说的
![image](https://user-images.githubusercontent.com/62897714/196232070-597c0960-73e5-4419-9947-e9fe7e279f85.png)
长杆看起来也不行

**Comment by iouter** [comment]
> ![image](https://user-images.githubusercontent.com/115782245/196218749-d7cf7c31-4944-49e7-b4e8-1a63dbd21eaf.png) 这种没有用%material的能汉化吗

因为这不是材料，只是它叫粉而已

**Comment by iouter** [comment]
> ![image](https://user-images.githubusercontent.com/115782245/196218452-a418d2b7-bbb8-4669-8d6c-2d7aae96b597.png) 双重板无法汉化

https://github.com/GTNewHorizons/GTplusplus/pull/405

**Comment by 8608029714** [comment]
2200的汉化还更新吗？

**Comment by iouter** [comment]
已全部修复，可以关闭
