### ISSUE TITLE
GT语言文件中，GT++相关材料汉化不一致

### ISSUE THREAD

**Issue by lycc193** [Kiwi233/Translation-of-GTNH#28]
![QQ图片20190928230351](https://user-images.githubusercontent.com/25812011/65818512-8f385d00-e244-11e9-88fe-fe4ada2e3a30.png)

**Comment by Kiwi233** [comment]
注意Key不一致，一个是流体一个是物品

**Comment by lycc193** [comment]
所以？物品能汉化 对应的流体不能汉化？

**Comment by Kiwi233** [comment]
你理解的汉化就是全是汉字才叫汉化？
生造而成的产物，原文就是这一堆化学式，你是要我把每个对应元素都翻出来么？

**Comment by lycc193** [comment]
所以我才拿对应的物品举例了 为什么同一个化学式 作为物品的时候可以汉化 作为流体就不可以

**Comment by lycc193** [comment]
![QQ图片20190930133726](https://user-images.githubusercontent.com/25812011/65852021-78e6ea00-e387-11e9-95ba-92b7d7b8b2f2.png)

**Comment by Kiwi233** [comment]
你放液体的原文呀，这玩意直译就是熔盐，还想怎么样。

**Comment by lycc193** [comment]
![QQ图片20190930134531](https://user-images.githubusercontent.com/25812011/65852407-9d8f9180-e388-11e9-864c-683f8e132457.png)
```Burnt LiFBeF2ThF4UF4 Salt``` 和 ```Cell of Molten Salt [LiFBeF2ThF4UF4]```

**Comment by lycc193** [comment]
我的意思是 同一个化学式 为什么在不同语言文件 和 不同物品/流体上 汉化**不一致**
而不是说 你的翻译有问题

**Comment by lycc193** [comment]
你这个汉化的截图... 不是统一的吗....

**Comment by Kiwi233** [comment]
没用过叫熔盐，用完叫用过的燃料单元，我就不吐槽为啥不用枯竭了
三个差不多的东西，就可以分成两种综合氟化物、复合氟化物
这个翻译质量可想而知

你可以注意一下mod自带的汉化和我的汉化包里的有什么区别，我已经在逐步修正这些低质量的翻译了，但没那么多精力逐个看

你提的这个问题我会在我自己的汉化包里统一修复的，也欢迎你找到更多的问题。

**Comment by lycc193** [comment]
熔盐和燃料单元 这是GT++的问题 原文就是这样的....
翻译应该先去遵从原文的吧....

**Comment by Kiwi233** [comment]
是的，GT++的作者很不靠谱，译者也不大靠谱，所以就很头疼

**Comment by lycc193** [comment]
未正式发布的版本 你们会进行汉化吗
比如[https://github.com/bartimaeusnek/bartworks/issues/38](url)

**Comment by Kiwi233** [comment]
我只关心GTNH，这个包的测试版我会提前进行汉化，如果这个mod在包里更新了我就会进行汉化
