### ISSUE TITLE
[反馈/建议]巫术：魔符学这本书最后一页没翻译

### ISSUE THREAD

**Issue by 8608029714** [Kiwi233/Translation-of-GTNH#287]
![image](https://user-images.githubusercontent.com/40914044/197104819-942cf39d-0f5d-4f52-983b-5a67bc2d055c.png)

**Comment by ChromicRedBrick** [comment]
英文原文也没有本地化，说明英语语言文件缺key

我这里先加上了，但不一定有用，因为Witchery是闭源的，不知道汉化zs能不能覆盖

![Witchery](https://user-images.githubusercontent.com/85604068/198769495-b35223ca-9d6a-4b4a-9a7f-2b0cec5c7d5e.png)

**Comment by ChromicRedBrick** [comment]
https://github.com/Kiwi233/Translation-of-GTNH/pull/290/commits/9229884b3c11979fd0d0670ad5a4ce33fd8f97fb

**Comment by Kiwi233** [comment]
![image](https://user-images.githubusercontent.com/42833050/214832695-e5194e1e-93d1-45d3-93ba-467d6fc53f93.png)

**Comment by iouter** [comment]
这是因为paratranz不在没有原文的情况下汉化
解决方法：专门开一个文件放这种没原文的key

**Comment by Kiwi233** [comment]
https://github.com/GTNewHorizons/WitcheryExtras/pull/20
