### ISSUE TITLE
[反馈/建议] GTPP 溢出停机 更正

### ISSUE THREAD

**Issue by hoshinokiseki** [Kiwi233/Translation-of-GTNH#291]
(没错 用了那个commit的标题
8b6ec0f7efadf8cf5848f179509ddcbdd658b7ce
上方commit刚刚好将正确的内容改错了，如果要用溢出停机来描述，应为：
interaction.voidexcess.enabled=禁用溢出停机
interaction.voidexcess.disabled=启用溢出停机

**Comment by ChromicRedBrick** [comment]
https://github.com/Kiwi233/Translation-of-GTNH/pull/292
