### ISSUE TITLE
[反馈/建议]当前版本Extra-Utilities.zs存在的问题

### ISSUE THREAD

**Issue by Merrg1n** [Kiwi233/Translation-of-GTNH#297]
1. 目前Github仓库中的Extra-Utilities.zs翻译出现乱码问题，具体为原UTF-8编码的翻译字符串使用了GB2312/GBK解码。
2. 游戏内如果使用"中文（中国）"，该研究对应的文本会丢失，具体原因如下：
```
game.setLocalization("en_US", "tc.research_name.EXURINGS", "Be free like a bird ... (Theorie)");
//more...
```
这里 `setLocalization` 指定了 `en_US`，导致不能正常显示翻译。
可能解决办法：把翻译词条写入 `resources/Extra Utilities[extrautils]/zh_CN.lang`

**Comment by Kiwi233** [comment]
新版本修改了zs中的汉化条目格式 @iouter 
具体实现效果测试中
