### ISSUE TITLE
Translation is not unified

### ISSUE THREAD

**Issue by BloCamLimb** [Kiwi233/Translation-of-GTNH#30]
You should unify your material translations, it causes much confusion to tell what actually it is

**Comment by BloCamLimb** [comment]
for example borosilicate glass, it's translated differently in mega EBF tooltip and the item, but neither is correct. additionally I saw many errors in quest book

**Comment by Kiwi233** [comment]
About the borosilicate glass, I translate it "硼玻璃", if you use my translation package correctly, you will find they are the same.

> additionally I saw many errors in quest book
Please point out the specific mistakes, I will correct them

**Comment by BloCamLimb** [comment]
我到时候PR吧
