### ISSUE TITLE
[反馈/建议] 给 ParaTranz 添加 hook

### ISSUE THREAD

**Issue by DancingSnow0517** [Kiwi233/Translation-of-GTNH#320]
当 ParaTranz 翻译有变化，自动更新同步到 github 并触发 workflow，以便及时得到更新的汉化

**Comment by MuXiu1997** [comment]
考虑过该方案, 但实际会有很多问题

- 为了更好迁移到 ParaTranz, 目前的工作流保持了迁移前的工作流, 便于 @Kiwi233 适应
- @Kiwi233 用分支的方式管理版本, ParaTranz 无法直接确定要同步的分支
- ParaTranz 未提供自定义 webhook

综上, 全自动化同步与现有工作流冲突, 且实现成本较高
