### ISSUE TITLE
在? 看看Angular Commit规范

### ISSUE THREAD

**Issue by Chenwe-i-lin** [Kiwi233/Translation-of-GTNH#34]
~~你们这个commit message怎么回事啊, 你们这是害人啊你们这个message~~

嗯,总之就是希望各位了解下 [`Conventional Commits`](https://semlinker.com/ng-verson-manage/) 这么一个Commit message规范.
举个例子:
```
add: updated 2.0,7.1 from the upstream.
update: updated Pam's Craft translate.
delete: deleted the wrong translate of some ores.
fix: 修复了模组xxx的颜色符号问题, 现在不会出现五彩缤纷的dropped items了
```

**Comment by Chenwe-i-lin** [comment]
另外,善用 `branch`

**Comment by Kiwi233** [comment]
这些规范关我啥事，目前只有我一个人在进行汉化，所有commit都是给我自己看的，我并不认为需要遵守什么所谓的规范，如果你想要让我改进这些，麻烦参与进来再说。

**Comment by Chenwe-i-lin** [comment]
非常抱歉, 一时冲动发出了不当的言论.
