### ISSUE TITLE
[反馈/建议]GT-PlusPlus-Book-Translation.jar会使游戏崩溃

### ISSUE THREAD

**Issue by superDoubleXZ** [Kiwi233/Translation-of-GTNH#341]
Master分支下mods文件夹里的GT-PlusPlus-Book-Translation.jar会导致游戏崩溃

GTNH版本为2.2.8

使用Java版本为：OpenJDK Runtime Environment (Zulu 8.66.0.15-CA-win64)

输出日志：https://pastebin.ubuntu.com/p/YfYR53qrHV/

**Comment by Kiwi233** [comment]
新分支内已经删除
