### ISSUE TITLE
[反馈/建议]可能是2.3.1的汉化导致的崩溃、无法更改语言、无法载入世界

### ISSUE THREAD

**Issue by BurNingcl0ud** [Kiwi233/Translation-of-GTNH#397]
GTNH2.3.1，java8

231装汉化后在语言设置设置成中文导致崩溃，未装汉化时没有这个问题。（paste.ubuntu.com/p/BSMDyvVwdM/）
此时仍然可以回到主菜单，但是切换语言不成功，仍然是英文。

此时仍然可以通过修改配置文件的方式将游戏语言改成中文，但是一加载完进入游戏就会提示（paste.ubuntu.com/p/Y8Hw66sVWj/）

此时回到主界面，创建世界，在载入世界时卡死（paste.ubuntu.com/p/GZCkn8sCP9/）

以上问题均在未安装汉化的GTNH2.3.1中未出现

**Comment by Kiwi233** [comment]
txloader问题，232版本修复
