### ISSUE TITLE
[反馈/建议]betterquests 出现问题

### ISSUE THREAD

**Issue by AirJerryWhite** [Kiwi233/Translation-of-GTNH#398]
无法正常检索任务物品，无法领取任务奖励。重新加载任务书后也无法完成和领取任务。
存档从2.2.3版本更新至2.3.2
[latest.log](https://github.com/Kiwi233/Translation-of-GTNH/files/11257680/latest.log)

**Comment by Kiwi233** [comment]
这个问题需要到gtnh仓库反馈
