### ISSUE TITLE
[反馈/建议] 版本2.3.3 磷酸钙翻译错误

### ISSUE THREAD

**Issue by wrsnk** [Kiwi233/Translation-of-GTNH#418]
应该是元素磷，但是翻译为了磷酸钙，相关各种配方和元素复制都是磷 单质

**Comment by Kiwi233** [comment]
代码自动填充 看清楚原文

**Comment by wrsnk** [comment]
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/41511851/4eeefd27-67ae-48be-a3ec-390dccf86b4a)


有些奇怪，矿物词典是对的，但是这边显示的名称不对

**Comment by Kiwi233** [comment]
不知 看更新吧
