### ISSUE TITLE
[反馈/建议]oc glasses翻译问题

### ISSUE THREAD

**Issue by Tree-er233** [Kiwi233/Translation-of-GTNH#422]
键位设置里，oc glasses被翻译成oc玻璃，应为oc眼镜。汉化包的版本为2.3.3
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/bad54906-52ad-4c05-96ad-47e762981711)

**Comment by iouter** [comment]
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/62897714/14ba7193-cbf3-4664-8845-56ad2c671530)
已修
