### ISSUE TITLE
[反馈/建议]

### ISSUE THREAD

**Issue by Game3239054693** [Kiwi233/Translation-of-GTNH#434]
2.3.0的汉化有恶性bug，我在gtnh萌新群下载的整合包并玩了几小时一切正常，加上汉化之后打开含有The Spice of Life模组中物品的箱子(还是我之前没加汉化时自己放的)或者拾起该Mod物品会立即导致崩溃，无法正常游玩

**Comment by Game3239054693** [comment]
崩溃报告如下:
[crash-2023-08-28_11.35.40-client.txt](https://github.com/Kiwi233/Translation-of-GTNH/files/12450053/crash-2023-08-28_11.35.40-client.txt)
现已完全无法游玩

**Comment by Kiwi233** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12696
