### ISSUE TITLE
[反馈/建议]采矿无人机MK-I和MK-II名称错误

### ISSUE THREAD

**Issue by Tree-er233** [Kiwi233/Translation-of-GTNH#474]
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/f674e8dd-b311-4f28-9138-845f82f83d75)
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/4407713b-f11c-4fe5-bfcd-f1480fbb46c0)
如图，都多了V，蓝色字体的序号是原名

**Comment by Mobius0526** [comment]
你这个显示原名的mod是什么啊

**Comment by Tree-er233** [comment]
> 你这个显示原名的mod是什么啊

https://github.com/RealSilverMoon/Untranslator
