### ISSUE TITLE
[反馈/建议]超级箱文本提示换行不当

### ISSUE THREAD

**Issue by Mobius0526** [Kiwi233/Translation-of-GTNH#475]
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/62875887/f1590fc4-70b2-4c22-9412-7632882f6022)
如图
使用螺丝刀启用和下面一句不应该换行

**Comment by Kiwi233** [comment]
这并不是同一字段通过换行符换行，而是有三段tooltip词条，所以只能强行分段了

**Comment by iouter** [comment]
可以：
物品过量销毁模式启用后，拆卸
后可保留其中物品

**Comment by Kiwi233** [comment]
感觉更变扭
