### ISSUE TITLE
[反馈/建议]ME接口中的高级阻挡模式提示过长，超出屏幕

### ISSUE THREAD

**Issue by Tree-er233** [Kiwi233/Translation-of-GTNH#481]
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/6072a7e7-a9a1-4dda-94c1-98addeca5dcb)
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/1fd11ba2-483d-411a-a0e9-5bb25d4c91f5)

如图，提示过长超出了屏幕，希望能加个换行🙂

**Comment by iouter** [comment]
https://github.com/Kiwi233/Translation-of-GTNH/issues/481
