### ISSUE TITLE
[反馈/建议]大型硅岩反应堆tooltip问题

### ISSUE THREAD

**Issue by Tree-er233** [Kiwi233/Translation-of-GTNH#505]
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/6b67f73c-619d-4b49-af38-eb0ac66296c0)
![image](https://github.com/Kiwi233/Translation-of-GTNH/assets/110247896/d9a13e3f-8531-4162-927d-64d5eb30ffc8)
如图，望修复

**Comment by Kiwi233** [comment]
请更新版本

**Comment by Tree-er233** [comment]
确实，我更新了2.4.1的汉化，已经修复
