### ISSUE TITLE
文件里存在未汉化部分。

### ISSUE THREAD

**Issue by InTheManXG** [Kiwi233/Translation-of-GTNH#52]
里面的盐矿石显示的是salt矿石，金矿是Gold矿石。

还有所有的贫瘠的xxx矿石，中间的部分全是英文的，我想应该是由于引用造成的问题，汉化文本中的部分，都是%material来替代，而被引用部分未汉化导致的问题。

我想能不能解决一下这个问题，吧这部分的汉化完善一下，非常感谢。

**Comment by Kiwi233** [comment]
罪魁祸首是bartworks覆盖了部分GT矿石，此前版本没有这个问题。
而且你说的应该是电子扫描仪的显示问题，以及NEI矿脉显示，此前都是没有问题的，material在主语言文件中均有翻译，否则一大批矿石、导线等均会出问题。

**Comment by InTheManXG** [comment]
感谢回复，那么这样的情况，有什么样的方式可以解决这个问题呢。
还有发现就是“更好的桶”这个mod里面的升级插件乱码，我之前是自己打开了里面的语言文件进行修改，解决了这个问题。类似于这样的乱码是翻译文本的问题，还是我们打开的方式不对呢。
![QQ图片20200309010712](https://user-images.githubusercontent.com/61611989/76167549-62e51d00-61a2-11ea-80d5-e83b327ae82e.png)
非常感谢大神能百忙之中抽空回答。

**Comment by Kiwi233** [comment]
这是龙之进化的手册，曾经尝试过用汉化包覆盖本体中的手册文件，但无效，必须是mod本体内修改才有效。目前打算跟DreamMaster商量一下，fork这个mod修改后重新发布，不过最近比较忙。。。

**Comment by InTheManXG** [comment]
我有一个提议，就是在您下一版本的汉化补丁中，直接加入一个修改后的mod，这样当我们进行汉化文件替换时，就可以直接替换掉有问题的汉化mod，包括“更好的桶”mod的问题，可以一同解决。您觉得这样是否可行。感谢回复。

**Comment by Kiwi233** [comment]
再次纠正是龙之研究。。。
修改后重新发布mod可能存在版权问题，所以最稳妥的方法还是与作者商量，由他修改后发布。
单机与服务器汉化问题的已知解决方式是服务端和客户端都打上汉化补丁，如果无法解决的话我也没有太好的办法。。。

**Comment by InTheManXG** [comment]
好的，非常感谢。

**Comment by mslxl** [comment]
你好，可不可以我们用 asm 编写一个mod，通过在运行时用汉化的字符串常量引用替换掉原本英文版的字符串常量引用，这样的话可以在实现汉化的同时又可以避免对原 mod 进行修改

**Comment by Kiwi233** [comment]
我不会。。。我先和DM交流一下吧，正好还有个极限末地生存的手册也必须在本体才能生效，这个他已经答应了。如果不行的话再试试你说的办法吧。

**Comment by Kiwi233** [comment]
龙研手册乱码问题我已经跟作者说了，应该会在更新后修复。
HEE的手册有点问题，因为这个作者不开源，只能尝试邮件联系原作者了，估计希望不大。。。

**Comment by InTheManXG** [comment]
非常感谢。同时替我服的玩家向您表达感谢。
我下载了最新的汉化在2088上，igi的显示好像有点问题，还有主界面的文字变成了乱码，是因为版本不匹配吗？？还是我的操作问题。我尝试了几遍依旧如此。

**Comment by Kiwi233** [comment]
主界面乱码问题是json内中文字符造成，已修复。
igi乱码问题是此版本删除了这些tag造成的，听说后续版本会重新加入，所以暂时不对igi做出修改。

**Comment by mslxl** [comment]
我后来研究了一下，由于 jvm 的保护机制，如果使用 asm 修改 mod 的话必须使用于汉化的 mod 拿到 forge 的持有的 classloader，然后由 用于汉化的 mod 来加载其他 mod，这样的话非常麻烦还存在着许多兼容性问题，而 coremod 又只能修改 minecraft，因此基本是对这个方法判了死刑。

如果不对 HEE 的mod文件进行修改的话想要进行汉化，个人观点是基本不可能，也许可以模仿 ForgeGradle  提供汉化文件和工具(或者修改方式)，让用户来对 mod 文件的修改，不知是否可行？

**Comment by Kiwi233** [comment]
只能如此了。。。提供语言文件让自己加到jar里头，但我感觉只有小部分人会看到。。。

**Comment by InTheManXG** [comment]
大佬你好，我又来麻烦你了。不知大佬是否可以汉化一下GT++的手册，感激不尽。
我觉得提供语言文件是可以的，一般来说，会下载汉化的普遍是腐竹，他们会自己打包客户端，打包时替换语言文件，是没问题的。
![QQ图片20200326161420](https://user-images.githubusercontent.com/61611989/77624501-e2356780-6f7c-11ea-9677-7900a61423e4.png)
![QQ图片20200326161414](https://user-images.githubusercontent.com/61611989/77624507-e3ff2b00-6f7c-11ea-845a-876bc58bdbea.png)

**Comment by Kiwi233** [comment]
GT++手册不在语言文件中，怀疑是硬编码，我无能为力只能联系作者，然后Alk又是一只大鸽子。

**Comment by InTheManXG** [comment]
好的，感谢回复。大佬加油！！！

**Comment by mslxl** [comment]
![Snipaste_2020-03-27_22-33-23](https://user-images.githubusercontent.com/11132880/77766733-024b5080-707b-11ea-9bd7-a7e73973f00c.png)
的确是硬编码了，在`gtPlusPlus.core.handler.BookHandler`里面

如果不通过作者修改实现汉化的话可以提供一个工具给用户，让用户通过运行来修改 `gtPlusPlus.core.handler.BookHandler` 的常量池来实现汉化的目的（大概原理像`hhclass`一样），这种方式您看怎么样？

如果您认为可行的话这个工具可以由我来写，最近我正好在学习 java 字节码

**Comment by Kiwi233** [comment]
先看我跟作者沟通结果吧，如果不行的话那就麻烦你写这个工具吧，感谢帮助！ 
@mslxl

**Comment by Kiwi233** [comment]
极限末地生存的手册问题，我终于联系上作者并获得了授权，下个版本的GTNH将会修复此问题，汉化文件作者是 @Athloniux ，我将对其进行校对统一以适应GTNH。

**Comment by Kiwi233** [comment]
@mslxl 
可能真的需要麻烦你写这个工具了，Alk并不愿意将这些硬编码添加本地化。

**Comment by mslxl** [comment]
已经开始写了，不出意外的话再过两天应该就能完工

[仓库](https://github.com/mslxl/hhjar)

**Comment by jadelaglace** [comment]
@mslxl

借个楼，提个小问题
QF是指什么，我在版本号和readme文件里都没发现相关信息

**Comment by jadelaglace** [comment]
@Kiwi233 

借个楼，提个小问题
QF是指什么，我在版本号和readme文件里都没发现相关信息

**Comment by CatSayInk** [comment]
> @Kiwi233
> 
> 借个楼，提个小问题
> QF是指什么，我在版本号和readme文件里都没发现相关信息

QuickFix

**Comment by Clores-Sky** [comment]
> 感谢回复，那么这样的情况，有什么样的方式可以解决这个问题呢。
> 还有发现就是“更好的桶”这个mod里面的升级插件乱码，我之前是自己打开了里面的语言文件进行修改，解决了这个问题。类似于这样的乱码是翻译文本的问题，还是我们打开的方式不对呢。
> ![QQ图片20200309010712](https://user-images.githubusercontent.com/61611989/76167549-62e51d00-61a2-11ea-80d5-e83b327ae82e.png)
> 非常感谢大神能百忙之中抽空回答。

你好大佬借楼问下你的更好的桶汉化乱码是咋解决的

**Comment by albus12138** [comment]
> GT++手册不在语言文件中，怀疑是硬编码，我无能为力只能联系作者，然后Alk又是一只大鸽子。

做了个用 Sponege Mixin 翻译 GT++ 手册的 mod，[仓库地址](https://github.com/albus12138/GT-pluslus-Book-Translation)

**Comment by Kiwi233** [comment]
顺利解决GT++手册汉化，感谢帮助
