### ISSUE TITLE
[反馈/建议]GTNH Java17版本汉化失效

### ISSUE THREAD

**Issue by paopaochen180** [Kiwi233/Translation-of-GTNH#540]
GTNH版本：2.5.1 java17版
汉化版本：nightly-2024-03-13
Java版本：java17.0.7

加了汉化其他物品都有汉化，只有GT物品未汉化

**Comment by Kiwi233** [comment]
使用对应版本汉化

**Comment by iouter** [comment]
原因应该是现在GregTech.lang改版了，把GregTech.lang改名为GregTech_zh_CN.lang试试

**Comment by iouter** [comment]
或许你再更新一点nightly版本，大概就有自带汉化了
