### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by moshan1997** [Kiwi233/Translation-of-GTNH#55]
![image](https://user-images.githubusercontent.com/39846845/76702961-cde5a500-6708-11ea-80d1-42f6cf9a73b7.png)
这个原文是Grind or not Grind
这里的Grind不是指研磨，而是指类似"肝"的意思吧。
意思就是这里的任务是可以去肝一下，也可以无视的。

**Comment by Kiwi233** [comment]
好像有一定道理，我琢磨琢磨

**Comment by Kiwi233** [comment]
我问了几个团队内成员，他们都不确定到底是什么意思，目前负责任务书的人在休假，暂时联系不上

**Comment by Kiwi233** [comment]
![image](https://user-images.githubusercontent.com/42833050/77538346-8c0fe800-6eda-11ea-877f-603635fe0064.png)
根据作者反馈，不用修正，保持原样

**Comment by moshan1997** [comment]
这个Grind肯定是verb的，就是意思可能有狭义。不过没什么关系，也就是我个人见解罢了。

**Comment by Wegifan** [comment]
此处grind应该是指“获取大量物品使自己变强”之意，可能可以翻译成“打磨自己”或“磨炼”等，在[Urban Dictionary](https://www.urbandictionary.com/define.php?term=grind)上有个解释称是MMO流传下来的，我觉得不应翻译成简单的磨碎。@Kiwi233

**Comment by Kiwi233** [comment]
> 此处grind应该是指“获取大量物品，花费大量功夫使自己变强”之意，可能可以翻译成“打磨自己”、“磨炼”甚至“折磨”等。
> 同时英文区称一个modpack “grindy” 指的是需要通过重复劳动完成一个目标。
> 在[Urban Dictionary](https://www.urbandictionary.com/define.php?term=grind)上有个解释称是MMO流传下来的。
> 我觉得不应简单地翻译成磨碎。
> @Kiwi233

作者自己不明白自己写的意思，需要你来教？

**Comment by moshan1997** [comment]
你这问题就没问好n or v可还行，我去问问看梦大师吧。

**Comment by Wegifan** [comment]
> > 此处grind应该是指“获取大量物品，花费大量功夫使自己变强”之意，可能可以翻译成“打磨自己”、“磨炼”甚至“折磨”等。
> > 同时英文区称一个modpack “grindy” 指的是需要通过重复劳动完成一个目标。
> > 在[Urban Dictionary](https://www.urbandictionary.com/define.php?term=grind)上有个解释称是MMO流传下来的。
> > 我觉得不应简单地翻译成磨碎。
> > @Kiwi233
> 
> 作者自己不明白自己写的意思，需要你来教？
> 请翻译一下 grinding a rock into bits 中grind的意思

您的问题就没有问好，跟词性有何关系？您用错误的问题获取到是正确答案的概率是微乎其微的。
同时我认为我的语气、表达方式是很好的，至少没有冒犯您的意思，我向你征求意见而您却直接向我发起人身攻击，您又是几个意思？我指出证据证明你的翻译有待商榷有何问题？希望心平气和地讨论翻译，谢谢。

**Comment by Kiwi233** [comment]
首先这些任务线是最初就有的，不是我翻译的，上来一个没头没脑的翻译错误这个标题就让人很恼火了，我是心平气和地去询问了好多人，得出了结论并关闭了issue。
现在又翻出来了，既然觉得我问得不对那就自己问去并给我记录。人身攻击那你就太敏感了。
动词磨碎、名词苦差事

**Comment by Wegifan** [comment]
![image](https://user-images.githubusercontent.com/49618165/87225075-d7340500-c3bc-11ea-9b9f-5410f2aafbc4.png)

> 现在又翻出来了，既然觉得我问得不对那就自己问去并给我记录。

我询问了梦想大师，我觉得他这意思不是直译。
>人身攻击那你就太敏感了。

我觉得你那句话论谁都感觉不爽……

**Comment by CatSayInk** [comment]
> > 此处grind应该是指“获取大量物品，花费大量功夫使自己变强”之意，可能可以翻译成“打磨自己”、“磨炼”甚至“折磨”等。
> > 同时英文区称一个modpack “grindy” 指的是需要通过重复劳动完成一个目标。
> > 在[Urban Dictionary](https://www.urbandictionary.com/define.php?term=grind)上有个解释称是MMO流传下来的。
> > 我觉得不应简单地翻译成磨碎。
> > @Kiwi233
> 
> 作者自己不明白自己写的意思，需要你来教？
> 请翻译一下 grinding a rock into bits 中grind的意思

我也觉得这句话  --作者自己不明白自己写的意思，需要你来教？-- 非常的令人不愉快

**Comment by moshan1997** [comment]
@Kiwi233

**Comment by Kiwi233** [comment]
当然令人不愉快，因为我当时也很不愉快。本来就对这个issue标题不太爽，求证后关闭又翻出来，我就认为没好好看记录当然就怼回去了。
反馈错误需要有切实根据，否则就是讨论。
现在有了根据，的确是我的问题，请提供翻译建议。 @Wegifan

**Comment by Kiwi233** [comment]
![image](https://user-images.githubusercontent.com/42833050/87226052-d2268400-c3c3-11ea-8ef5-909ef023b0ed.png)
当时也不是没问过大师，直接给我个不确定，然后再找的任务书作者求证
