### ISSUE TITLE
任务id 1021 存在笔误

### ISSUE THREAD

**Issue by marionette-curtain** [Kiwi233/Translation-of-GTNH#57]
[L4089](https://github.com/Kiwi233/Translation-of-GTNH/blob/master/resources/minecraft/lang/zh_CN.lang#L4089)
应为"你可以使用过硫酸钠来蚀刻电路板"而不是“你可以使用过硫酸钠来时刻电路板”

**Comment by Kiwi233** [comment]
感谢反馈！
