### ISSUE TITLE
2.0.9.0FQ4任务书没汉化玩吧

### ISSUE THREAD

**Issue by Clores-Sky** [Kiwi233/Translation-of-GTNH#66]
![image](https://user-images.githubusercontent.com/42526110/85458988-47c4de80-b5d4-11ea-8aba-8c4b797269cc.png)
![image](https://user-images.githubusercontent.com/42526110/85459021-527f7380-b5d4-11ea-8f4a-9c0ba244408d.png)
新的火箭燃料下面有新的主线任务 用了刷新方块还是英文的 是任务书还没汉化玩吗

**Comment by Kiwi233** [comment]
自己看了语言文件再来反馈

**Comment by Clores-Sky** [comment]
我看了汉化文本确实是有汉化但是不知道为啥进游戏里面打开就这些新的任务没有中文以前的那些任务都有更新方块和指令我也用过了 也开过新档测试过但是还是一样
![image](https://user-images.githubusercontent.com/42526110/85546472-82b82800-b64f-11ea-9608-555c7f1437d9.png)
![image](https://user-images.githubusercontent.com/42526110/85546660-b5fab700-b64f-11ea-8b13-4d9fdcbba3de.png)

**Comment by Clores-Sky** [comment]
而且有部分新任务有显示汉化
![image](https://user-images.githubusercontent.com/42526110/85546938-fc501600-b64f-11ea-92ee-ff0403fdc121.png)
![image](https://user-images.githubusercontent.com/42526110/85546972-03772400-b650-11ea-8ccc-caf727fd6112.png)

**Comment by Kiwi233** [comment]
既然语言文件里有那么就应该找找自己的问题

**Comment by Clores-Sky** [comment]
你好 我想我找到问题的所在了 我是从release上面下载的完整版汉化 然后汉化书里面的zh_cn.lag文件里面貌似可能是格式问题 如图左侧为从release处下载的zh_cn.lag右侧为Clone or download那边下载的zh_cn.lag文件我发现了未汉化的部分前面都多出了一个空格 可能是这个格式问题所以汉化不成功 当我更换为从Clone or download那边 下载的zh_cn.lag文件我的问题解决了 最后谢谢你为GTNH这个整合包一直持续更新汉化内容 感谢！
![image](https://user-images.githubusercontent.com/42526110/85550646-c14fe180-b653-11ea-9dd4-50a7865e8ee3.png)
![image](https://user-images.githubusercontent.com/42526110/85553577-acc11880-b656-11ea-9eb5-d883b5369193.png)
