### ISSUE TITLE
binniecore 词条缺失

### ISSUE THREAD

**Issue by albus12138** [Kiwi233/Translation-of-GTNH#68]
林业多个电子管中由binniecore添加的词条缺失（按shift查看详细信息）

binniecore.beemodifier.genetic_decay

**Comment by Kiwi233** [comment]
![image](https://user-images.githubusercontent.com/42833050/89612883-82988280-d8b3-11ea-8ead-5c008c494e54.png)
Key出了问题，需要进一步检查生成
