### ISSUE TITLE
电子探矿机就算设置到普通矿物模式还是会扫描到贫瘠

### ISSUE THREAD

**Issue by foxwhite25** [Kiwi233/Translation-of-GTNH#71]
版本：2.0.9.1a（以前也有）
应该发生的：电子探矿机就算设置到普通矿物模式只会扫描到普通矿脉，而没有贫瘠，在没汉化之前是正常的。
现在的情况：汉化之后再扫描会在普通模式扫到贫瘠矿石，虽然没什么大碍，就是眼花。
![image](https://user-images.githubusercontent.com/39846845/99978561-0fbf0300-2de1-11eb-8556-63158f9ee734.png)
![image](https://user-images.githubusercontent.com/39846845/99978592-18afd480-2de1-11eb-8339-82441189a7bb.png)
为什么觉得是汉化导致的：因为在实施汉化之前没有这个问题，不清楚是不是我的问题。

**Comment by foxwhite25** [comment]
@albus12138 你看看106，110行，看起来是用small来判定是否是贫瘠的，汉化把开头变成贫瘠所以他不认了

**Comment by albus12138** [comment]
@foxwhite25 行吧。。改的时候没仔细看，看他检测了unlocalizedname就没管了，我再改一下给梦带师发个pr

**Comment by albus12138** [comment]
@foxwhite25 修好了，梦带师那边更新得下个版本了，可以先用我build的 [下载](https://github.com/albus12138/DetravScannerMod/releases/download/1.5.7-fixed/GT.Scanner.Mod-1.5.7.jar)

需要在 Gregtech.lang里面加一行
`    S:gt.scanner.small_ore.keyword=贫瘠`

![2020-11-25 11-13-19 的屏幕截图](https://user-images.githubusercontent.com/9742081/100178646-4430dd00-2f0f-11eb-9557-3ae7673b0156.png)

**Comment by foxwhite25** [comment]
好的
