### ISSUE TITLE
小砖块和合成后的方块都叫焦炉砖

### ISSUE THREAD

**Issue by iouter** [Kiwi233/Translation-of-GTNH#74]
![c1](https://user-images.githubusercontent.com/62897714/103533259-bcec6700-4ec7-11eb-93e4-5b87e2d1905d.jpg)
![c2](https://user-images.githubusercontent.com/62897714/103533264-c2e24800-4ec7-11eb-8ed1-ee727c23cc19.jpg)
如题，二者都叫焦炉砖，建议把合成后的易名为焦炉砖块。

类似的，高级焦炉砖最好也一样改名。

**Comment by Kiwi233** [comment]
不错的建议
