### ISSUE TITLE
#2667 #2672任务介绍中锌离子应为锡离子

### ISSUE THREAD

**Issue by iouter** [Kiwi233/Translation-of-GTNH#77]
![QQ截图20210126111025](https://user-images.githubusercontent.com/62897714/105795032-24796c00-5fc7-11eb-9d8e-b235401237ed.jpg)
![QQ截图20210126111032](https://user-images.githubusercontent.com/62897714/105795023-23483f00-5fc7-11eb-8e87-94658e1fe63f.jpg)

**Comment by Kiwi233** [comment]
感谢反馈，已更正。
