### ISSUE TITLE
关于流体名称汉化

### ISSUE THREAD

**Issue by GlodBlock** [Kiwi233/Translation-of-GTNH#95]
![image](https://user-images.githubusercontent.com/60341015/123362039-a5eb1f80-d5a2-11eb-88ff-018c41999453.png)
bart的那些流体可以通过添加
fluid.XXXX=XXXX来进行汉化（XXX为流体英文名）
像王水就是
fluid.Aqua Regia=王水
空格和大小写都要一致

**Comment by iouter** [comment]
大部分只是体力活，这事我可以做了

**Comment by Kiwi233** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/589
